name: test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Download LLVM, botan, libgtk-3-dev
        run: sudo apt-get install llvm-11 clang-11 libbotan-2-dev botan libgtk-3-dev
      - name: build odin
        working-directory: ./Odin
        run: ./build_odin.sh release
      - name: build test/init-only
        run: ./Odin/odin build test/init-only.odin -file -out=init-only.bin
      # no run here because it appears to not work as action.
      # but I manually test (on my machine lol)
      #- name: run tests
      #  run: ./test.bin
      - name: build test/simple
        run: ./Odin/odin build test/simple.odin -file -out=simple.bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu
          path: |
            init-only.bin
            simple.bin

  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: build Odin
        working-directory: ./Odin
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          ./build.bat 1
      - name: build tests
        run: ./Odin/odin build test/init-only.odin -file -out='./init-only.exe' -resource='./windows/libui.rc'
      - name: run tests
        run: ./init-only.exe
      - name: build test/simple
        run: ./Odin/odin build test/simple.odin -file -out='./simple.exe' -resource='./windows/libui.rc'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Win
          path: |
            init-only.exe
            simple.exe

  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Download LLVM, botan and setup PATH
        run: |
          brew install llvm@13 botan
          echo "/usr/local/opt/llvm@13/bin" >> $GITHUB_PATH
          TMP_PATH=$(xcrun --show-sdk-path)/user/include
          echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
      - name: build odin
        working-directory: ./Odin
        run: ./build_odin.sh release
      - name: build test/init-only
        run: ./Odin/odin build test/init-only.odin -file -out=init-only.bin
      - name: run tests
        run: ./init-only.bin
      - name: build test/simple
        run: ./Odin/odin build test/simple.odin -file -out=simple.bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macOS
          path: |
            init-only.bin
            simple.bin
